name: CI

on: [push]

jobs:
  build-Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - name: Build
        run: for dir in */; do cd $dir; for dir in */; do cd $dir; for sln in *.sln; do dotnet build $sln; cd ..
      - name: Test with the dotnet CLI
        run: for dir in */; do cd $dir; for sln in *.sln; do dotnet test $sln
